### ISSUE TITLE
ModuleNotFoundError: No module named 'caffe2'

### ISSUE THREAD

**Issue by naumanshah007** [facebookresearch/Clinical-Trial-Parser#24]
when i execute this command:-

(base) macbook@macbooks-MacBook-Pro Clinical-Trial-Parser-main % pytext train < src/resources/config/ner.json

following is error which arrise despite i installed caffe and all other dependencies. moreover, also tried all possible solutions on git posted by others to solve but still having the issue in my macbook:-

Traceback (most recent call last):
  File "/Users/macbook/opt/anaconda3/bin/pytext", line 5, in <module>
    from pytext.main import main
  File "/Users/macbook/opt/anaconda3/lib/python3.9/site-packages/pytext/__init__.py", line 8, in <module>
    from caffe2.python import workspace
ModuleNotFoundError: No module named 'caffe2'

Please apprise the solution or make a docker image to encounter all such issues.

Thanking you in anticipation

**Comment by victormurcia** [comment]
> when i execute this command:-
> 
> (base) macbook@macbooks-MacBook-Pro Clinical-Trial-Parser-main % pytext train < src/resources/config/ner.json
> 
> following is error which arrise despite i installed caffe and all other dependencies. moreover, also tried all possible solutions on git posted by others to solve but still having the issue in my macbook:-
> 
> Traceback (most recent call last): File "/Users/macbook/opt/anaconda3/bin/pytext", line 5, in from pytext.main import main File "/Users/macbook/opt/anaconda3/lib/python3.9/site-packages/pytext/**init**.py", line 8, in from caffe2.python import workspace ModuleNotFoundError: No module named 'caffe2'
> 
> Please apprise the solution or make a docker image to encounter all such issues.
> 
> Thanking you in anticipation

I'm having the same issue. I've tried a variety of different things like using different Python versions, dependency install methods, and CUDA version but no luck.

**Comment by ryota3915** [comment]
Commented in the [Link](https://github.com/facebookresearch/Clinical-Trial-Parser/issues/26#issuecomment-1475456029)
Hope this helps.
I use Ubuntu 18.04.6 LTS, python3.7 and annaconda for package management.
